### ISSUE TITLE
I can reproduce the segmentation fault

### ISSUE THREAD

**Issue by mjbstldc** [meska/mjpeg_stream_webcam#9]
On my system, if I open the stream in a browser, I can cause the fault by: 
(1) refreshing the browser, which causes another get request
(2) opening another browser, causing another get request.

I'm running it with Octoprint on a mac mini with Catalina 10.15.7  
The system and network environment is very stable and the camera is good.  

I imagine that there are other possible causes if the connection is unstable or the camera is glitchy, but this one is reproducible.  For instance, it ran all night no problem, and then as soon as I did (1) I saw a second get request on the server, and then crash.

**Comment by senseotech** [comment]
Also seeing this same reproducible issue running on Ventura 13.3; loading a second copy of OctoPrint (and thus the cam feed) segmentation faults and kills the program.
